### ISSUE TITLE
subject_alternative_names doesn't change, terraform still wants to recreate

### ISSUE THREAD

**Issue by reegnz** [terraform-aws-modules/terraform-aws-acm#20] opened 2019-09-25 15:53 UTC
Related issue: https://github.com/terraform-providers/terraform-provider-aws/issues/8531

Please introduce the workaround described there:
```
lifecycle {
  ignore_changes = ["subject_alternative_names"]
}
```

Until the issue above is fixed, this module cannot be used with multiple SAN-s without the ignore_changes hook being in place.

**Comment by antonbabenko** [comment] 2019-09-25 16:48
Hi @reegnz !

Please take a look at [complete-dns-validation example](https://github.com/terraform-aws-modules/terraform-aws-acm/blob/master/examples/complete-dns-validation/main.tf), where multiple SANs are used.

**Comment by reegnz** [comment] 2019-09-26 17:29
@antonbabenko I use 4 SAN-s and the more you use the higher the probability that the AWS API returns the San list in a different order. With only two the probability of them swapping places is just 50%.

Try running that example about 10 times and I'm sure you'll encounter this issue (that's the thing with randomness, it doesn't always change the order).

**Comment by antonbabenko** [comment] 2019-09-26 19:25
This is exactly the reason why there is some magic in the module:

https://github.com/terraform-aws-modules/terraform-aws-acm/blob/1d8e823cd08c9dcd2ffd2bd22a509c7633db253e/main.tf#L2-L6

If you can show the values you are trying to get I can maybe suggest the solution (you can replace domain name with something, but keep subdomains).

**Comment by reegnz** [comment] 2019-09-30 07:20
That magic doesn't fix the case when you have multiple subdomains in the SAN-s. That just filters out the wildcards.

**Comment by reegnz** [comment] 2019-09-30 07:33
Ok, so my current module parameters look something like this (domain changed for obvious purposes - you won't be able to verify with my domain):

```
locals {
  domain_name = "example.com"
}
module "cert" {
  source  = "terraform-aws-modules/acm/aws"
  version = "v2.3.0"
  domain_name = local.domain_name
  subject_alternative_names = [
    "*.${local.domain_name}",
    "api.${local.domain_name}",
    "*.api.${local.domain_name}",
    "infra.${local.domain_name}",
    "*.infra.${local.domain_name}",
  ]
}
```

Now in this case these are 5 SAN-s in the certificate. The order of those 5 will randomly change and that screws up the [aws_acm_certificate](https://www.terraform.io/docs/providers/aws/r/acm_certificate.html) change detection. Hence why this module is affected, since it makes use of the `aws_acm_certificate` resource.

Everything about this is also elaborated in detail in terraform-providers/terraform-provider-aws#8531, even how to work around that issue.

**Comment by antonbabenko** [comment] 2019-09-30 08:25
Yes, I am well aware of this issue in Terraform AWS provider and yet we can't add `subject_alternative_names` to `ignored_changes` because it will break this module for many users.

Also,
```
subject_alternative_names = [
    "*.${local.domain_name}",
    "api.${local.domain_name}",
    "*.api.${local.domain_name}",
    "infra.${local.domain_name}",
    "*.infra.${local.domain_name}",
  ]
```
is the same as:
```
subject_alternative_names = [
    "*.${local.domain_name}",
    "*.api.${local.domain_name}",
    "*.infra.${local.domain_name}",
  ]
```

**Comment by reegnz** [comment] 2019-09-30 13:50
It's broken either way for me, with ignore_changes I cannot modify the SAN when I need to, without it terraform recognizes the cert as changed even if it isn't and will recreate the cert.

I choose option 1 as the safer alternative and I guess that means I cannot use this module then.
That's a shame. ¯\_(ツ)_/¯

**Comment by reegnz** [comment] 2019-09-30 13:52
It's broken either way for me, with ignore_changes I cannot modify the SAN when I need to, without it terraform recognizes the cert as changed even if it isn't and will recreate the cert.

I choose option 1 as the safer alternative and I guess that means I cannot use this module then.
That's a shame. ¯\_(ツ)_/¯

by the way, I wonder who relies on that broken functionality if you say it will 'break' when it's already broken in a different way.

**Comment by xueshanf** [comment] 2019-10-13 19:30
I seem having issue with us-east-1 but not us-west-2.
About using lifecycle workaround, now about introducing  with an option "true" or "false"?

**Comment by DTTerastar** [comment] 2020-03-06 15:30
I'm having this issue in us-east-1

**Comment by kevingimbel** [comment] 2020-04-01 11:46
I'm having the same issue.

I'm using 

```hcl
  subject_alternative_names = [
    "*.${local.traefik_url}",
    "${local.traefik_url_no_prefix}",
    "*.${local.traefik_url_no_prefix}"
  ]
```

and the certificates are recreated on every apply which makes it hard to see if there is any "real" change in the infra. If this is expected behavior, as indicated above, I'll rewrite my code to not use the module.

**Comment by antonbabenko** [comment] 2020-04-01 12:03
As @xueshanf is saying, the problem is not on the module side but rather on the AWS API side, because it returns a different response for different regions&AWS accounts and there is no extra workaround in place on Terraform AWS provider side to make it consistent.

Honestly, I don't know what we can do in this module to get 100% working solution for 100% cases. There were several open issues in Terraform AWS provider which, I believe, should help us very much. Maybe someone can take a look into those if you have time.

@kevingimbel If you can take this module as basic and adjust it for your own needs it is great.

**Comment by kevingimbel** [comment] 2020-04-01 12:31
@antonbabenko I agree there isn't much you can do, and the only thing you _could_ do is have one resource with the lifecycle and one without, but that'd be duplicated code to maintain so -- not a good solution.

My case is very limited and for me it is no problem to set the lifecycle so I'll just do that.

**Comment by antonbabenko** [comment] 2020-04-01 12:33
Ok, if you (or anyone else) can make a PR and update documentation saying the reason for this, I will be glad to merge this as a workaround.

**Comment by kevingimbel** [comment] 2020-04-02 08:33
I don't think my solution is good.

I'd create a second resource like so (haven't tested this)
```hcl

resource "aws_acm_certificate" "this" {
  count = var.create_certificate && !var.validation_ignore_subject_alternative_names_changes  ? 1 : 0

  domain_name               = var.domain_name
  subject_alternative_names = var.subject_alternative_names
  validation_method         = var.validation_method

  tags = var.tags

  lifecycle {
    create_before_destroy = true
  }
}


resource "aws_acm_certificate" "this_ignore_changes" {
  count = var.create_certificate && var.validation_ignore_subject_alternative_names_changes ? 1 : 0

  domain_name               = var.domain_name
  subject_alternative_names = var.subject_alternative_names
  validation_method         = var.validation_method

  tags = var.tags

  lifecycle {
    create_before_destroy = true
    ignore_changes = [subject_alternative_names]
  }
}
```

and then assign the cert to a local variable.

```hcl
locals {
    this_cert = var.validation_ignore_subject_alternative_names_changes ? aws_acm_certificate.this_ignore_changes[0] : aws_acm_certificate.this[0]
}
```

all other resources could then use the `local.this_cert` variable. 

But as I said, I don't think this is a good solution. I don't think introducing a second, copy-pasted resource is justified for a workaround of an upstream API "issue".

For me, I'm totally fine with rolling my own cert management, I basically copied some of the code here and my certificate domains never change because they are part of a module. 

@antonbabenko If you're ok with these changes I could wrap them up in a PR.

**Comment by antonu17** [comment] 2020-04-30 13:54
Same here, all the time it wants to re-create certificates, because of subject_alternative_names change order every time.

**Comment by gdurandvadas** [comment] 2020-05-07 12:33
I'm having the same issue, even if I `sort` the list:
```
  subject_alternative_names = sort([
    "*.test.development.example.com",
    "*.development.example.com",
    "test.development.example.com",
  ])
```

**Comment by antonbabenko** [comment] 2020-05-07 12:50
@kevingimbel , I believe that there is no universal hack which we can easily apply in the module unless the root issue (https://github.com/terraform-providers/terraform-provider-aws/issues/8531) exists. As of now, it is the most upvoted issue in that repository with 288 upvotes.

I don't know what else we as community (not HashiCorp employees) can do to get this issue fixed in the provider. :(

**Comment by kevingimbel** [comment] 2020-05-08 09:56
@antonbabenko I don't think we can do anything really. 

For my case I simply refactored our internal terraform code and copied some of this modules' code in (like the locals from https://github.com/terraform-aws-modules/terraform-aws-acm/blob/master/main.tf#L1-L7).

Then I just added the lifecycle on the resource `aws_acm_certificate`.

```hcl
resource "aws_acm_certificate" "my_cert" {
[...]
  lifecycle {
    ignore_changes = [subject_alternative_names]
  }
}
```

But this works for us, it may not work for anyone and introducing a resource with ignored lifecycle and one without (as I suggested in my previous comment https://github.com/terraform-aws-modules/terraform-aws-acm/issues/20#issuecomment-607702444) is just a very weird workaround - I would not like to introduce that.

Unless terraform fixes the issue in the provider _or_ they allow to set ignores in modules I think there's nothing we, as a community, can do.

**Comment by reegnz** [comment] 2020-05-09 22:18
Just to chime in here, since I opened the issue.

I still regard the ignore_changes solution closest to usable behaviour. Even though it ignores changes in SAN, you can still taint the resource manually for recreation. 
If we don't ignore the SAN, there's basically no workaround like that, there will be no clean 'terraform plan' for you.

**Comment by mohsen0** [comment] 2020-06-16 12:55
small change to fix this https://github.com/terraform-aws-modules/terraform-aws-acm/pull/53

**Comment by antonbabenko** [comment] 2020-08-17 16:30
Finally, this issue has been solved in AWS provider version 3 - https://github.com/terraform-providers/terraform-provider-aws/issues/8531

There is nothing we should be doing in this module. Phew!

**Closed by antonbabenko** 2020-08-17 16:30 UTC

**Comment by antonbabenko** [comment] 2021-10-21 14:39
I believe the problem is not related to the module but to your terragrunt configuration. The original bug was fixed 1+ years ago in the provider.

**Comment by antonbabenko** [comment] 2021-10-29 18:30
Terraform 0.13 is the minimum version we are supporting in https://github.com/terraform-aws-modules .

In your case `subject_alternative_names` can be set just to one value - `"*.test.ignore.service.example.com"`
