### ISSUE TITLE
Call to function "element" failed: cannot use element function with an empty list.

### ISSUE THREAD

**Issue by roobert** [terraform-aws-modules/terraform-aws-acm#29] opened 2019-11-12 13:07 UTC
Hi, has anyone encountered this error?

Version
```
terraform 0.12.13
```

Manifest
```
module "acm" {
  source  = "github.com/terraform-aws-modules/terraform-aws-acm?ref=v2.3.0"

  zone_id                   = var.zone_id
  domain_name               = "example.com."
  validation_method         = "DNS"

  tags = {
    Terraform = "true"
  }
}
```

Error
```
module.sensu.module.sensu-server-elb.module.elb.aws_elb.this: Refreshing state... [id=sensu0]

Error: Error in function call

  on .terraform/modules/sensu.acm/main.tf line 27, in resource "aws_route53_record" "validation":
  27:   name    = element(local.validation_domains, count.index)["resource_record_name"]
    |----------------
    | count.index is 0
    | local.validation_domains is empty tuple

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on .terraform/modules/sensu.acm/main.tf line 28, in resource "aws_route53_record" "validation":
  28:   type    = element(local.validation_domains, count.index)["resource_record_type"]
    |----------------
    | count.index is 0
    | local.validation_domains is empty tuple

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on .terraform/modules/sensu.acm/main.tf line 32, in resource "aws_route53_record" "validation":
  32:     element(local.validation_domains, count.index)["resource_record_value"]
    |----------------
    | count.index is 0
    | local.validation_domains is empty tuple

Call to function "element" failed: cannot use element function with an empty
list.
```

Kind regards

**Comment by ledakis** [comment] 2019-11-26 00:14
Hey @roobert, can you check in your local copy in `.terraform/modules/sensu.acm/main.tf` if `v.domain_name` exists at line 6 and if yes to change it to `var.domain_name` ?

I had a similar problem and it seems to have been resolved by that.

**Comment by antonbabenko** [comment] 2019-12-19 18:58
Hi @roobert !

I think the issue is related to an ending `.` (dot) in `domain_name`. Make sure you remove it and use [v2.5.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.5.0) of this module.

Let me know if the issue persists (I think it will be fixed).

**Comment by ozonni** [comment] 2020-01-12 12:12
@antonbabenko i have the same issue and i don't have `.` in the end of domain name. But aws adds it to the end. Any ideas how to fix it?

**Comment by antonbabenko** [comment] 2020-01-12 12:16
You can use `trimsuffix` which became available not very long time ago in Terraform:

https://github.com/terraform-aws-modules/terraform-aws-acm/blob/795a6908199a7ec5ebfb3326cef499d18d2a8da9/examples/complete-dns-validation/main.tf#L7-L8

**Comment by ozonni** [comment] 2020-01-12 12:24
@antonbabenko still getting the same issue
```
Error: Error in function call

  on .terraform/modules/ecs.alb.acm/terraform-aws-modules-terraform-aws-acm-3c76105/main.tf line 27, in resource "aws_route53_record" "validation":
  27:   name    = element(local.validation_domains, count.index)["resource_record_name"]
    |----------------
    | count.index is 1
    | local.validation_domains is empty tuple

Call to function "element" failed: cannot use element function with an empty
list.
```

**Comment by antonbabenko** [comment] 2020-01-12 12:28
Please show the whole `module` block with values, and make sure you remove trailing dot from `domain_name`.

**Comment by ozonni** [comment] 2020-01-12 12:35
@antonbabenko 
```
locals {
  domain_name  = "*.${var.root_domain}"
}

module "acm" {
  source  = "terraform-aws-modules/acm/aws"
  version = "~> v2.0"

  domain_name  = trimsuffix(local.domain_name, ".")
  zone_id      = var.zone_id
}
```

**Comment by antonbabenko** [comment] 2020-01-12 13:20
`domain_name = var.root_domain` is enough. `domain_name` should not start with `*`.

**Comment by ozonni** [comment] 2020-01-12 13:58
@antonbabenko thx, seems like wildcard domain should be now specified in `subject_alternative_names`. Wasn't the case before. Thank you.

**Comment by antonbabenko** [comment] 2020-01-12 14:01
Good, I will close this issue.

**Closed by antonbabenko** 2020-01-12 14:01 UTC

**Comment by mignaulo** [comment] 2020-01-21 18:06
I think the fix here is actually to update the `distinct_domain_names` to something like
```
distinct_domain_names = distinct(concat([replace(var.domain_name, "*.", "")], [for s in var.subject_alternative_names : replace(s, "*.", "")]))
```
(replace `*.` on `domain_name` as well)

**Comment by antonbabenko** [comment] 2020-01-21 19:22
@mignaulo Without trying out, I think you can solve this in multiple ways.

The hardest part (and actually the main reasons for many issues with this module) is an inconsistent response in AWS/Terraform behavior.
